FROM tomcat:9-jdk8

ENV TZ=PRC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ADD myapp.war webapps/

ENTRYPOINT ["bin/startup.sh", "tail", "-f", "logs/catalina.out"]